services:
    Vinium\SyliusPayumUp2PayPlugin\Form\Type\Up2PayGatewayConfigurationType:
        tags:
            - { name: sylius.gateway_configuration_type, type: up2pay, label: 'Up2Pay' }
            - { name: form.type }
    vinium.up2pay.payment.factory:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: [ Vinium\SyliusPayumUp2PayPlugin\Payum\Up2PayGatewayFactory ]
        tags:
            - { name: payum.gateway_factory_builder, factory: up2pay }
    Vinium\SyliusPayumUp2PayPlugin\Payum\Action\ConvertPaymentAction:
        public: true
        arguments:
            - '@vinium.up2pay.payment.paybox_params'
        tags:
            - { name: payum.action, factory: up2pay, alias: payum.action.convert_payment }
    vinium.up2pay.payment.paybox_params:
        class: Vinium\SyliusPayumUp2PayPlugin\Payum\PayboxParams
        public: true
